### ISSUE TITLE
Link quebrado

### ISSUE THREAD

**Issue by ericpqmor** [brerodrigues/ratf-rev-pwn-class#1]
Primeiramente, parabéns pelo guia. Tô curtindo!
O link do chall (https://github.com/brerodrigues/CTFs/raw/master/teste) tá dando 404 :(

**Comment by brerodrigues** [comment]
Foi mal, deixei o guia meio abandonado, mas já consertei o [link](https://github.com/brerodrigues/CTFs/raw/master/my_challenges/hello_world_rev) do desafio e vou adicionar mais uns materiais. Valeu por avisar ;)
